### ISSUE TITLE
MultiANewArray not supported

### ISSUE THREAD

**Issue by ThisTestUser** [Konloch/bytecode-viewer#198] opened 2018-04-07 23:32 UTC
It says "unadded opcode".

**Comment by Konloch** [comment] 2019-04-14 01:59
Will be fixed in v2.9.16, I don't have a class file on hand that has the opcode though.

If anyone has one, please email me at Konloch@gmail.com or instead test v2.9.16 when it's out and let me know if it's working as intended, cheers!

**Closed by Konloch** 2019-04-14 01:59 UTC
