### ISSUE TITLE
UI Bug blank string on blank background

### ISSUE THREAD

**Issue by IMSD1238** [Konloch/bytecode-viewer#441] opened 2022-06-13 11:15 UTC
![Screenshot (9)](https://user-images.githubusercontent.com/107364573/173342030-782f89d2-9689-437f-90a8-9e3f71c88767.png)

**Comment by ThexXTURBOXx** [comment] 2022-06-13 16:34
![grafik](https://user-images.githubusercontent.com/12763829/173401541-c9b9d1a4-6fe1-46d2-9199-d97e4fad793a.png)

Not exactly reproducible on my machine. It also looks like you use an outdated version of BCV. Please consider updating.

However, **only in dark mode**, the text should not be black :)

**Comment by IMSD1238** [comment] 2022-06-14 09:16
> ![grafik](https://user-images.githubusercontent.com/12763829/173401541-c9b9d1a4-6fe1-46d2-9199-d97e4fad793a.png)
> 
> Not exactly reproducible on my machine. It also looks like you use an outdated version of BCV. Please consider updating.
> 
> However, **only in dark mode**, the text should not be black :)

i am using 2.11.2

**Comment by Konloch** [comment] 2023-02-21 01:07
Can you please include your JDK version / OS version

**Comment by Konloch** [comment] 2023-12-18 08:05
Sorry about the delay! A preview for this bug fix is located at https://github.com/Konloch/bytecode-viewer/actions/runs/7245057185 - it will be included in the next BCV release

**Closed by Konloch** 2023-12-18 08:05 UTC
Labels: Bug
