### ISSUE TITLE
Found an apk can not decompile

### ISSUE THREAD

**Issue by limelect** [Konloch/bytecode-viewer#56] opened 2015-07-04 15:40 UTC
Get in touch to send you the apk or download from market   Windfinder_1.9.3.apk

Bytecode Viewer Version: 2.9.6

java.io.FileNotFoundException: C:\Users\LimElect\.Bytecode-Viewer\bcv_temp\eMLngxtvvwYrJCSTAkyJteXmHueLenzT.apk (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadResources(JarUtils.java:80)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:627)

Bytecode Viewer Version: 2.9.6

brut.a.a.e: resource spec: 0x01010462
	at brut.a.d.a.d.b(Unknown Source)
	at brut.a.d.a.g.a(Unknown Source)
	at brut.a.d.a.g.a(Unknown Source)
	at brut.a.d.a.a.q.c(Unknown Source)
	at brut.a.d.a.a.t.a(Unknown Source)
	at brut.a.d.a.a(Unknown Source)
	at brut.a.d.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:626)

**Comment by Konloch** [comment] 2015-07-05 15:37
Could you please mirror this APK somewhere so I can test it? Cheers.

**Comment by limelect** [comment] 2015-07-08 09:10
https://dl.dropboxusercontent.com/u/91173792/Windfinder_1.9.3.apk

**Comment by Konloch** [comment] 2015-07-08 19:49
Thanks!

**Comment by Konloch** [comment] 2015-07-08 19:50
Confirmed fixed on 2.9.7, could you please verify it on your end by using this jar?

https://github.com/Konloch/bytecode-viewer/blob/master/BytecodeViewer%202.9.7-preview.jar

Cheers!

**Comment by limelect** [comment] 2015-07-09 06:39
It Ok but plz add 2 things
1. Which file am i working on?
2. Which pan hold which decompile
     just add the name of the pan i am using ON EACH PAN
     and it will be nice also if it is writable or not
Other wise perfect thanks

**Comment by Konloch** [comment] 2015-07-09 15:30
fixed

**Comment by Konloch** [comment] 2015-07-09 15:30
1) This probably won't be added because you can work on mutliple jars at once inside of BCV
2) Not sure what you mean by this

Could you open another ticket for this requests though?

Cheers!

**Closed by Konloch** 2015-07-09 15:30 UTC

**Comment by Konloch** [comment] 2015-07-09 15:34
Ah ok, I see what you mean for number 2. I'll work on that today to see if i can pull something off.

**Comment by limelect** [comment] 2015-07-09 20:32
Thanks
When you assign a pan a decoder so which pan is assigned what?
I think you got it.
as for 1 i add a file.Above the pans there is written "work space " just add to which file name. 
AS SINCE I DO NOT SEE THE LOGIC BEHIND ADDING SOURCES.
P.S the software got stack once and i had to restart the computer !
I will try to figure it out as i add a few APK's.
