### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nsonaniya2010** [Konloch/bytecode-viewer#350] opened 2021-08-28 07:52 UTC
```
Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.10.16 [Fat Jar], OS: Mac OS X, Java: 1.8.0_302

java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1967)
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:178)
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:111)
	at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:209)
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:193)
	at org.objectweb.asm.ClassVisitor.visitMethod(ClassVisitor.java:366)
	at com.googlecode.d2j.dex.Dex2Asm.collectBasicMethodInfo(Dex2Asm.java:330)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:639)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:526)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:428)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:542)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:135)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:235)
	at the.bytecode.club.bytecodeviewer.util.Dex2Jar.dex2Jar(Dex2Jar.java:42)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.APKResourceImporter.open(APKResourceImporter.java:66)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:88)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:60)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ThexXTURBOXx** [comment] 2021-08-29 19:46
I've seen this error for some users already.
Are you able to share the DEX file, so I can debug the problem?

**Please only share the DEX file if you have the appropriate legal rights to do so. If not, please share the link to the Google Play Entry or some other uploader.**

**Comment by nsonaniya2010** [comment] 2021-08-30 01:15
Here it is: https://play.google.com/store/apps/details?id=com.koo.app

**Comment by ThexXTURBOXx** [comment] 2021-08-30 08:44
Thanks for sharing! It is not easy to fix that, but I will try my best. Actually, JADX, for example, also faces this exact problem.

**Comment by nsonaniya2010** [comment] 2021-09-01 16:10
Thanks.

**Comment by ThexXTURBOXx** [comment] 2021-09-04 20:31
This error should be "fixed" in [this release](https://github.com/Konloch/bytecode-viewer/suites/3683946849/artifacts/89746958). Can you confirm that this is the case? :)

There will be lots of warnings in the command line since I added a fix that works around this issue by responding to specific exceptions from ASM. Please, also note that methods and/or fields that can't be decompiled successfully now are `abstract` and their types are `java.lang.Object`. This is about the same workaround that `jadx` added (https://github.com/skylot/jadx/commit/009939f8662354ad5fae88015f6d30f55bafa66f), but it is much uglier in `dex2jar` :)

**Comment by nsonaniya2010** [comment] 2021-09-05 05:32
Thanks a lot. I will check it.

**Comment by nsonaniya2010** [comment] 2021-09-05 06:02
I checked it. The above issue got fixed.
However when I see the class files they're not properly categorized in the folders for example the main app.
I checked the same with JADX and found out to be working pretty well in categorizing the classes in proper folders. 
Can you look into it as well?

**Comment by ThexXTURBOXx** [comment] 2021-09-05 09:00
Thanks for reporting back! It's very nice to see that the issue is kinda "fixed" :)
About the categorization: I am unsure if I understand correctly.
With the newest build of BCV, your decompiled APK looks like this (a small snippet):
![grafik](https://user-images.githubusercontent.com/12763829/132121178-e42f2d1d-58fb-4005-8b5a-abb0976695bc.png)

In JADX, it looks like this:
![grafik](https://user-images.githubusercontent.com/12763829/132121194-01e316df-c460-401c-a02b-802ba6a50f35.png)

As you can see, `dex2jar` is organizing all classes as-is, i.e. if a class is relocated/obfuscated into the default package (e.g. class `a` had another name in some package before, but was obfuscated into the default package as class `a`), then it will be in the default package as well after `dex2jar` consumed it.
JADX, on the other hand, introduces a package called `defpackage`, which now contains all the classes that were obfuscated into the DEFault PACKAGE before (hence the name `defpackage`).
I don't know which approach is the best, but I actually prefer the way `dex2jar` is handling it. Maybe I will add some switch at some point, which you can use to relocate classes from the default package into some `defpackage`, but this will be purely optional, since I don't want to break existing procedures that rely on that :)

That all being said, I will let this issue open until I further looked into this.

**Comment by nsonaniya2010** [comment] 2021-09-05 14:20
Thats Cool. Thanks a lot & Thanks for promptly replying.

**Closed** 2021-09-11 03:06 UTC
Labels: Bug, Dependency Related, Android
